### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by jnluy** [lucydot/effmass#14]
The test failed on a new installation of effmass on Python 3.6.

**Comment by lucydot** [comment]
Hello, thanks for flagging this up - can you give me a couple of more details so I can trace the problem - which test failed?

**Comment by jnluy** [comment]
Hi. I made a fresh install of python 3.6.8. And then followed the
instructions in the readme.

pip3 install --user effmass

python3 -m pytest

The error log is attached. The same happens for python3.7.


Am Do., 16. Mai 2019 um 16:11 Uhr schrieb Lucy Whalley <
notifications@github.com>:

**Comment by lucydot** [comment]
Hello, I'm afraid the error log isn't attached - I think you will need to log into github and drag and drop the file (https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests). Automated testing of effmass happens [here](https://travis-ci.com/lucydot/effmass), and it seems to be passing all tests, so I'm a little stumped why it is failing for you - might be something system dependant. Just to check that you are running the `python3 -m pytest` command from inside the effmass folder? (`pip3 show effmass` will tell you where effmass is installed)

**Comment by jnluy** [comment]
[err.log](https://github.com/lucydot/effmass/files/3190989/err.log)

**Comment by bjmorgan** [comment]
This looks like it might be an issue introduced by a recent change to the `vasppy` API, which is used to parse the `PROCAR` files. If so, it should be fixed in this pull request: https://github.com/lucydot/effmass/pull/15

**Comment by lucydot** [comment]
Hi, thanks @bjmorgan for submitting the PR request - this has been merged with `effmass`, and I have made a new release (v1.1.0) which should now be available through PyPI. @jnluy if you update `effmass` via pip it should pass all tests 🤞

**Comment by lucydot** [comment]
Once you confirm the problem is fixed @jnluy I'll close the issue - thanks again for flagging it up.
-Lucy

**Comment by jnluy** [comment]
pytest still fails, but with another error now
[err2.log](https://github.com/lucydot/effmass/files/3201603/err2.log)

**Comment by bjmorgan** [comment]
> pytest still fails, but with another error now
> [err2.log](https://github.com/lucydot/effmass/files/3201603/err2.log)

The error log appears to show the old version of `effmass`. Can you please check what version you have installed using `pip list`?

**Comment by jnluy** [comment]
> > pytest still fails, but with another error now
> > [err2.log](https://github.com/lucydot/effmass/files/3201603/err2.log)
> 
> The error log appears to show the old version of `effmass`. Can you please check what version you have installed using `pip list`?

You are right. I was sitting in the wrong folder when calling pytest. Thank you for the quick fix!

**Comment by lucydot** [comment]
Thanks to PR #15 from @bjmorgan the latest versions of `vasppy` and `effmass` are now compatible with each other and so I am closing this issue.
